import ts from "typescript";
import fs from "fs";
import crypto from "crypto";
import path from "path";
import Hashids from "hashids";
import { transformNode } from "../transformations/transformNode";
import { PathTranslator } from "./rojoResolver/pathTranslator";
import { RojoResolver } from "./rojoResolver/rojoResolver";
import { Cache } from "../util/cache";
import { getPackageJson } from "../util/functions/getPackageJson";
import { BuildInfo } from "./buildInfo";
import { Logger } from "./logger";
import { assert } from "./rojoResolver/util/assert";
import { SymbolProvider } from "./symbolProvider";
import { f } from "../util/factory";
import { isPathDescendantOf } from "../util/functions/isPathDescendantOf";
import { ClassInfo } from "../types/classes";
import { CallMacro } from "../transformations/macros/macro";
import { CALL_MACROS } from "../transformations/macros/call/callMacros";
import { isCleanBuildDirectory } from "../util/functions/isCleanBuildDirectory";
import { parseCommandLine } from "../util/functions/parseCommandLine";
import { createPathTranslator } from "../util/functions/createPathTranslator";
import { arePathsEqual } from "../util/functions/arePathsEqual";
import { GenericIdOptions } from "../util/functions/getGenericIdMap";
import { NodeMetadata } from "./nodeMetadata";

const IGNORE_RBXTS_REGEX = /node_modules\/@rbxts\/(compiler-types|types)\/.*\.d\.ts$/;

export interface TransformerConfig {
	/**
	 * An internal option that should not be used.
	 * This is used to compile the framework package, turning this on in your game will cause many errors.
	 */
	$rbxpackmode$?: boolean;

	/**
	 * Disables TypeScript's own semantic diagnostics.
	 * Improves performance, but results in increased risk of incorrect compilation as well as messed up diagnostic spans.
	 */
	noSemanticDiagnostics?: boolean;

	/**
	 * This is the salt used for hashes generated by Flamework.
	 * Defaults to a randomly generated 64 byte salt.
	 */
	salt?: string;

	/**
	 * This can be used to lower collision chance with packages.
	 * Defaults to package name.
	 */
	hashPrefix?: string;

	/**
	 * Whether to automatically generate the identifiers for exports.
	 * This is recommended for packages but it is not recommended to
	 * enable this in games.
	 */
	preloadIds?: boolean;

	/**
	 * Whether to enable flamework's obfuscation.
	 *
	 * This comprises of:
	 * 1. random event names
	 * 2. shortened ids
	 */
	obfuscation?: boolean;
}

export class TransformState {
	public parsedCommandLine = parseCommandLine();
	public currentDirectory = this.parsedCommandLine.project;
	public options = this.program.getCompilerOptions();
	public srcDir = this.options.rootDir ?? this.currentDirectory;
	public outDir = this.options.outDir ?? this.currentDirectory;
	public typeChecker = this.program.getTypeChecker();

	public symbolProvider = new SymbolProvider(this);
	public classes = new Map<ts.Symbol, ClassInfo>();

	public rojoResolver?: RojoResolver;
	public pathTranslator!: PathTranslator;
	public buildInfo!: BuildInfo;

	public rootDirectory: string;
	public packageName: string;
	public isGame: boolean;

	public callMacros = new Map<ts.Symbol, CallMacro>();
	public genericIdMap?: Map<ts.Symbol, GenericIdOptions>;
	public inferExpressions = new Map<ts.SourceFile, ts.Identifier>();
	public isUserMacroCache = new Map<ts.Symbol, boolean>();

	private setupBuildInfo() {
		let baseBuildInfo = BuildInfo.fromDirectory(this.currentDirectory);
		if (!baseBuildInfo || (Cache.isInitialCompile && isCleanBuildDirectory(this.options))) {
			if (this.options.incremental && this.options.tsBuildInfoFile) {
				if (ts.sys.fileExists(this.options.tsBuildInfoFile)) {
					throw new Error(`Flamework cannot be built in a dirty environment, please delete your tsbuildinfo`);
				}
			}
			baseBuildInfo = new BuildInfo(path.join(this.currentDirectory, "flamework.build"));
		}
		this.buildInfo = baseBuildInfo;

		const candidates = Cache.buildInfoCandidates ?? [];
		if (!Cache.buildInfoCandidates) {
			Cache.buildInfoCandidates = candidates;
			const candidatesSet = new Set<string>();
			for (const file of this.program.getSourceFiles()) {
				const buildCandidate = BuildInfo.findCandidateUpper(path.dirname(file.fileName));
				if (
					buildCandidate &&
					!arePathsEqual(buildCandidate, baseBuildInfo.buildInfoPath) &&
					!candidatesSet.has(buildCandidate)
				) {
					candidatesSet.add(buildCandidate);
					candidates.push(buildCandidate);
				}
			}
		}

		for (const candidate of candidates) {
			const relativeCandidate = path.relative(this.currentDirectory, candidate);
			const buildInfo = BuildInfo.fromPath(candidate);
			if (buildInfo) {
				Logger.infoIfVerbose(`Loaded buildInfo at ${relativeCandidate}, next id: ${buildInfo.getLatestId()}`);
				baseBuildInfo.addBuildInfo(buildInfo);
			} else {
				Logger.warn(`Build info not valid at ${relativeCandidate}`);
			}
		}
	}

	private setupRojo() {
		this.pathTranslator = createPathTranslator(this.program);

		const rojoConfig = RojoResolver.findRojoConfigFilePath(this.currentDirectory);
		if (rojoConfig) {
			const rojoContents = fs.readFileSync(rojoConfig, { encoding: "ascii" });
			const sum = crypto.createHash("md5").update(rojoContents).digest("hex");

			if (sum === Cache.rojoSum) {
				this.rojoResolver = Cache.rojoResolver;
			} else {
				this.rojoResolver = RojoResolver.fromPath(rojoConfig);
				Cache.rojoSum = sum;
				Cache.rojoResolver = this.rojoResolver;
			}
		}
	}

	constructor(
		public program: ts.Program,
		public context: ts.TransformationContext,
		public config: TransformerConfig,
	) {
		this.setupRojo();
		this.setupBuildInfo();

		const { result: packageJson, directory } = getPackageJson(this.currentDirectory);
		this.rootDirectory = directory;
		assert(packageJson.name);

		this.packageName = packageJson.name;
		this.isGame = !this.packageName.startsWith("@");

		if (!this.isGame) config.hashPrefix ??= this.packageName;
		this.buildInfo.setIdentifierPrefix(config.hashPrefix);

		if (config.hashPrefix?.startsWith("$") && !config.$rbxpackmode$) {
			throw new Error(`The hashPrefix $ is used internally by Flamework`);
		}

		Cache.isInitialCompile = false;
	}

	isUserMacro(symbol: ts.Symbol) {
		const cached = this.isUserMacroCache.get(symbol);
		if (cached !== undefined) return cached;

		if (symbol.declarations) {
			for (const declaration of symbol.declarations) {
				const metadata = new NodeMetadata(this, declaration);
				if (metadata.isRequested("macro")) {
					this.isUserMacroCache.set(symbol, true);
					return true;
				}
			}
		}

		this.isUserMacroCache.set(symbol, false);
		return false;
	}

	private areMacrosSetup = false;
	setupMacros() {
		if (this.areMacrosSetup) return;
		this.areMacrosSetup = true;

		for (const macro of CALL_MACROS) {
			const symbols = macro.getSymbol(this);
			if (Array.isArray(symbols)) {
				for (const symbol of symbols) {
					this.callMacros.set(symbol, macro);
				}
				macro._symbols = symbols;
			} else {
				this.callMacros.set(symbols, macro);
				macro._symbols = [symbols];
			}
		}
	}

	public fileImports = new Map<string, ImportInfo[]>();
	addFileImport(file: ts.SourceFile, importPath: string, name: string): ts.Identifier {
		const symbolProvider = this.symbolProvider;

		if (importPath === "@flamework/core") {
			if (
				(file === symbolProvider.flameworkFile.file ||
					this.getSymbol(file) === symbolProvider.flameworkFile.fileSymbol) &&
				name === "Flamework"
			) {
				return f.identifier("Flamework");
			}

			const flameworkDir = path.dirname(symbolProvider.flameworkFile.file.fileName);
			const modulePath = path.join(flameworkDir, name === "Reflect" ? "reflect" : "flamework");

			if (isPathDescendantOf(file.fileName, flameworkDir)) {
				importPath = "./" + path.relative(path.dirname(file.fileName), modulePath) || ".";
			}
		}

		let importInfos = this.fileImports.get(file.fileName);
		if (!importInfos) this.fileImports.set(file.fileName, (importInfos = []));

		let importInfo = importInfos.find((x) => x.path === importPath);
		if (!importInfo) importInfos.push((importInfo = { path: importPath, entries: [] }));

		let identifier = importInfo.entries.find((x) => x.name === name)?.identifier;
		if (!identifier) {
			if (!file.identifiers.has(name)) {
				identifier = f.identifier(name);
				importInfo.entries.push({ name, identifier });
			}
		}

		if (!identifier) {
			start: for (const statement of file.statements) {
				if (!f.is.importDeclaration(statement)) break;
				if (!f.is.string(statement.moduleSpecifier)) continue;
				if (!f.is.importClauseDeclaration(statement.importClause)) continue;
				if (!f.is.namedImports(statement.importClause.namedBindings)) continue;
				if (statement.moduleSpecifier.text !== importPath) continue;

				for (const importElement of statement.importClause.namedBindings.elements) {
					if (importElement.propertyName) {
						if (importElement.propertyName.text === name) {
							identifier = importElement.name;
							break start;
						}
					} else {
						if (importElement.name.text === name) {
							identifier = importElement.name;
							break start;
						}
					}
				}
			}
		}

		if (!identifier) importInfo.entries.push({ name, identifier: (identifier = f.identifier(name, true)) });

		return identifier;
	}

	getSourceFile(node: ts.Node) {
		const parseNode = ts.getParseTreeNode(node);
		if (!parseNode) throw new Error(`Could not find parse tree node`);

		return ts.getSourceFileOfNode(parseNode);
	}

	getSymbol(node: ts.Node, followAlias = true): ts.Symbol | undefined {
		if (f.is.namedDeclaration(node)) {
			return this.getSymbol(node.name);
		}

		const symbol = this.typeChecker.getSymbolAtLocation(node);

		if (symbol && followAlias) {
			return ts.skipAlias(symbol, this.typeChecker);
		} else {
			return symbol;
		}
	}

	hash(id: number) {
		const hashPrefix = this.config.hashPrefix;
		const salt = this.config.salt ?? this.buildInfo.getSalt();
		const hashGenerator = new Hashids(salt, 2);
		if (this.isGame && !hashPrefix) {
			return `${hashGenerator.encode(id)}`;
		} else {
			// If the package name is namespaced, then it can be used in
			// other projects so we want to add a prefix to the Id to prevent
			// collisions with other packages or the game.
			return `${hashPrefix ?? this.packageName}:${hashGenerator.encode(id)}`;
		}
	}

	obfuscateText(text: string, context?: string) {
		return this.config.obfuscation ? this.buildInfo.hashString(text, context) : text;
	}

	public hasErrors = false;
	addDiagnostic(diag: ts.DiagnosticWithLocation) {
		if (diag.category === ts.DiagnosticCategory.Error) {
			this.hasErrors = true;
		}

		this.context.addDiagnostic(diag);
	}

	public hoistedToTop = new Map<ts.SourceFile, ts.Statement[]>();
	hoistToTop(file: ts.SourceFile, node: ts.Statement) {
		let hoisted = this.hoistedToTop.get(file);
		if (!hoisted) this.hoistedToTop.set(file, (hoisted = []));

		hoisted.push(node);
	}

	private prereqStack = new Array<Array<ts.Statement>>();
	capture<T>(cb: () => T): [T, ts.Statement[]] {
		this.prereqStack.push([]);
		const result = cb();
		return [result, this.prereqStack.pop()!];
	}

	prereq(statement: ts.Statement) {
		const stack = this.prereqStack[this.prereqStack.length - 1];
		if (stack) stack.push(statement);
	}

	prereqList(statements: ts.Statement[]) {
		const stack = this.prereqStack[this.prereqStack.length - 1];
		if (stack) stack.push(...statements);
	}

	isCapturing(threshold = 1) {
		return this.prereqStack.length > threshold;
	}

	transform<T extends ts.Node>(node: T): T {
		return ts.visitEachChild(node, (newNode) => transformNode(this, newNode), this.context);
	}

	transformNode<T extends ts.Node>(node: T): T {
		return ts.visitNode(node, (newNode) => transformNode(this, newNode));
	}

	transformList<T extends ts.Node>(nodes: ts.NodeArray<T>): ts.NodeArray<T> {
		return ts.visitNodes(nodes, (newNode) => transformNode(this, newNode));
	}

	private _shouldViewFile(file: ts.SourceFile) {
		const fileName = path.posix.normalize(file.fileName);
		if (IGNORE_RBXTS_REGEX.test(fileName)) return false;

		const buildCandidates = Cache.buildInfoCandidates!;
		for (const candidate of buildCandidates) {
			let realPath = Cache.realPath.get(candidate);
			if (!realPath) Cache.realPath.set(candidate, (realPath = fs.realpathSync(candidate)));

			const candidateDir = path.dirname(realPath);
			if (
				isPathDescendantOf(file.fileName, candidateDir) &&
				!isPathDescendantOf(file.fileName, path.join(candidateDir, "node_modules"))
			) {
				return true;
			}
		}

		return false;
	}

	shouldViewFile(file: ts.SourceFile) {
		const cached = Cache.shouldView?.get(file.fileName);
		if (cached !== undefined) return cached;

		const result = this._shouldViewFile(file);
		Cache.shouldView.set(file.fileName, result);

		return result;
	}
}

interface ImportItem {
	name: string;
	identifier: ts.Identifier;
}

interface ImportInfo {
	path: string;
	entries: Array<ImportItem>;
}
